[build]
publish = "."

[[redirects]]
from = "/"
to = "/frontend/index.html"
status = 200

[[redirects]]
from = "/assets/*"
to = "/frontend/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "https://REPLACE_WITH_RENDER_BACKEND_URL/api/:splat"
status = 200
force = true
